/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package openstars.storage.bigset;


@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.12.0)", date = "2019-08-24")
public enum TErrorCode implements org.apache.thrift.TEnum {
  EGood(0),
  ENoRootMeta(1),
  ECouldNotConnectMetadata(2),
  ECouldNotConnectIDGen(3),
  ECouldNotConnectSmallSet(4),
  ECouldNotConnectRootMetaMapping(5),
  EItemNotExisted(100),
  EUnknownException(10),
  EBigSetNotExisted(101),
  EBigSetCreated(102),
  EBigSetAlreadyExisted(103),
  EBigSetAssigned(104);

  private final int value;

  private TErrorCode(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  @org.apache.thrift.annotation.Nullable
  public static TErrorCode findByValue(int value) { 
    switch (value) {
      case 0:
        return EGood;
      case 1:
        return ENoRootMeta;
      case 2:
        return ECouldNotConnectMetadata;
      case 3:
        return ECouldNotConnectIDGen;
      case 4:
        return ECouldNotConnectSmallSet;
      case 5:
        return ECouldNotConnectRootMetaMapping;
      case 100:
        return EItemNotExisted;
      case 10:
        return EUnknownException;
      case 101:
        return EBigSetNotExisted;
      case 102:
        return EBigSetCreated;
      case 103:
        return EBigSetAlreadyExisted;
      case 104:
        return EBigSetAssigned;
      default:
        return null;
    }
  }
}
